version: '2'
services:
    printing_service-app:
        image: printing_service
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://printing_service-postgresql:5432/printing_service
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    printing_service-postgresql:
        extends:
            file: postgresql.yml
            service: printing_service-postgresql
